<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="desktop1" failures="4" tests="8" name="Data Driven User module Test" time="12.203" errors="0" timestamp="2024-07-15T15:39:47 BDT">
  <testcase classname="api.tests.DDtests.test_DDTCreateUser" name="test_creteuser" time="1.534">
    <failure type="java.lang.AssertionError" message="message should contain ok message expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: message should contain ok message expected [true] but found [false]
at api.tests.DDtests.test_DDTCreateUser.test_creteuser(test_DDTCreateUser.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_creteuser -->
  <testcase classname="api.tests.DDtests.test_DDTCreateUser" name="test_creteuser" time="1.307">
    <failure type="java.lang.AssertionError" message="message should contain ok message expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: message should contain ok message expected [true] but found [false]
at api.tests.DDtests.test_DDTCreateUser.test_creteuser(test_DDTCreateUser.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_creteuser -->
  <testcase classname="api.tests.DDtests.test_DDTCreateUser" name="test_creteuser" time="1.299">
    <failure type="java.lang.AssertionError" message="message should contain ok message expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: message should contain ok message expected [true] but found [false]
at api.tests.DDtests.test_DDTCreateUser.test_creteuser(test_DDTCreateUser.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_creteuser -->
  <testcase classname="api.tests.DDtests.test_DDTCreateUser" name="test_creteuser" time="1.397">
    <failure type="java.lang.AssertionError" message="message should contain ok message expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: message should contain ok message expected [true] but found [false]
at api.tests.DDtests.test_DDTCreateUser.test_creteuser(test_DDTCreateUser.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_creteuser -->
  <testcase classname="api.tests.DDtests.test_DDTDeleteUser" name="test_deleteuser" time="1.416"/>
  <testcase classname="api.tests.DDtests.test_DDTDeleteUser" name="test_deleteuser" time="1.397"/>
  <testcase classname="api.tests.DDtests.test_DDTDeleteUser" name="test_deleteuser" time="1.289"/>
  <testcase classname="api.tests.DDtests.test_DDTDeleteUser" name="test_deleteuser" time="1.339"/>
  <testcase classname="api.test.BaseClass" name="@BeforeSuite setupData" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupData -->
  <testcase classname="api.test.BaseClass" name="@BeforeSuite beforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase classname="api.test.BaseClass" name="@AfterSuite afterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
</testsuite> <!-- Data Driven User module Test -->
